version: 2
jobs:
  build:
    working_directory: ~/WB001
    docker: # use the docker executor type; machine and macos executors are also supported
    - image: circleci/openjdk
    - image: circleci/mariadb:10
      envirmoment:
        MYSQL_ALLOW_EMPTY_PASSWORD: yes
        MYSQL_ROOT_PASSWORD: ''
        MYSQL_DATABASE: springdb
    steps:
    - checkout # check out the code in the project directory
    - run: sudo apt-get update
    - run: sudo apt-get install mysql-client
    - run: sudo mysql -ve "CREATE USER 'spring'@'localhost' IDENTIFIED BY 'spring'"


